repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.11
    hooks:
      - id: uv-lock
      - id: uv-export

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']  # Allow larger files for notebooks
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
