"""Type stubs for lightgbm package."""

from typing import Any

class LGBMClassifier:
    """Type stub for LightGBM classifier."""

    booster_: Any
    n_estimators: int

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def fit(self, *args: Any, **kwargs: Any) -> Any: ...
    def predict(self, *args: Any, **kwargs: Any) -> Any: ...
    def predict_proba(self, *args: Any, **kwargs: Any) -> Any: ...

class Booster:
    """Type stub for LightGBM Booster."""

    def dump_model(self) -> Any: ...
    def trees_to_dataframe(self) -> Any: ...

def __getattr__(name: str) -> Any: ...
