"""Type stubs for catboost package."""

from typing import Any

import numpy as np

class _CatBoostBase:
    """Internal CatBoost object exposed via model._object."""

    def _get_tree_count(self) -> int: ...
    def _get_tree_splits(self, tree_idx: int, pool: "Pool") -> list[str]: ...
    def _get_tree_leaf_values(self, tree_idx: int) -> list[float]: ...
    def _get_tree_leaf_counts(self) -> list[int]: ...

class Pool:
    def __init__(
        self,
        data: Any,
        label: Any = ...,
        *,
        cat_features: list[int] | list[str] | None = ...,
        baseline: Any = ...,
    ) -> None: ...
    def get_label(self) -> np.ndarray: ...
    def get_feature_names(self) -> list[str]: ...
    _feature_names: list[str] | None

class CatBoostClassifier:
    tree_count_: int
    feature_names_: list[str]
    _object: _CatBoostBase

    def __init__(self, **kwargs: Any) -> None: ...
    def fit(
        self,
        X: Any,
        y: Any = ...,
        *,
        init_model: Any = ...,
        cat_features: list[int] | list[str] | None = ...,
        **kwargs: Any,
    ) -> "CatBoostClassifier": ...
    def predict(self, data: Any, *, prediction_type: str = ..., **kwargs: Any) -> np.ndarray: ...
    def predict_proba(self, data: Any, **kwargs: Any) -> np.ndarray: ...
    def get_all_params(self) -> dict[str, Any]: ...
    def get_cat_feature_indices(self) -> list[int]: ...
    def calc_leaf_indexes(self, data: Any) -> np.ndarray: ...
    def get_feature_importance(self, *, type: str = ..., data: Any = ...) -> np.ndarray: ...

def __getattr__(name: str) -> Any: ...
